defaults: &defaults 
  cloud_crowd_server:	http://localhost:8080
  server_root:          localhost:1234
  aws_zone:             us-east-1c
  preconfigured_ami_id: ami-11a4b57801aae468
  ssl_on:               true

development:
  <<: *defaults
  ssl_on:             false

staging:
  <<: *defaults
  cloud_crowd_server: ec2-50-16-197-147.compute-1.amazonaws.com:8080
  server_root:        staging.documentcloud.org
  asset_root:         "//s3.amazonaws.com/dcloud_staging"

production:
  <<: *defaults
  cloud_crowd_server: http://localhost:8080
  server_root:        54.197.224.62
  asset_root:         "//s3.amazonaws.com/dactyl-docs"
  db_volume_id:       vol-d4c305bd

test:
  <<: *defaults
