production:
  solr:
    hostname: localhost
    port: 7377
    path: /solr/collection1
    read_timeout: 5
    open_timeout: 1.5
    log_level: INFO
    min_memory: 200M
    max_memory: 3G
    pid_dir: tmp/pids

development:
  solr:
    hostname: localhost
    port: 7377
    path: /solr/collection1
    log_level: ALL
    min_memory: 20M
    max_memory: 200M
    pid_dir: tmp/pids

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/collection1
    pid_dir: tmp/pids

staging:
  solr:
    hostname: localhost
    port: 7377
    log_level: WARNING
    pid_dir: tmp/pids
    path: /solr/collection1
    read_timeout: 5
    open_timeout: 1.5
    min_memory: 200M
    max_memory: 3G
