# Sensitive API keys and other secret strings.

defaults : &defaults
  aws_access_key: 
  aws_secret_key: 
  calais_license: 
  smtp_password:  
  pixel_ping:     DocumentCloud               # The secret hashed key for Pixel Ping (keep in sync with secrets/pixel_ping/:env.json)
  guest_username: guest                       # The username used for logging into basic auth in staging
  guest_password: DocumentCloud               # The password used for logging into basic auth in staging
  username:       documentcloud               # The database username
  db_password:    documentcloudVirtualMachine # The database password
  db_host:        localhost                   # the hostname for your database server
  solr_host:      localhost                   # the hostname for your solr server

development :
  <<: *defaults

staging :
  <<: *defaults
  db_host:        # the hostname for your database server
  solr_host:      # the hostname for your solr server
  job_end_point:  # the hostname for your cloud-crowd server
  central_server: # the fully qualified (private) url for the cloud-crowd server (e.g. http://ip-44-555-66-777.ec2.internal:8080)

test :
  <<: *defaults

production :
  <<: *defaults
  db_host:        # the hostname for your database server
  solr_host:      # the hostname for your solr server
  job_end_point:  # the hostname for your cloud-crowd server
  central_server: # the fully qualified (private) url for the cloud-crowd server (e.g. http://ip-44-555-66-777.ec2.internal:8080)
